generatorName: java
outputDir: ./out
globalProperties:
  skipFormModel: true
additionalProperties:
  groupId: org.nightscoutfoundation
  artifactId: nocturne
  artifactVersion: "0.1.0"
  apiPackage: org.nightscoutfoundation.nocturne.api
  modelPackage: org.nightscoutfoundation.nocturne.model
  invokerPackage: org.nightscoutfoundation.nocturne
  library: native
  serializationLibrary: jackson
  licenseName: AGPL-3.0-only
  sourceFolder: src/main/java
  java8: false
  dateLibrary: java8
  openApiNullable: true
  useJakartaEe: true
